# bot config variables
# invite link: https://discord.com/oauth2/authorize?client_id=992079193686945873&scope=bot&permissions=8

token: "OTkyMDc5MTkzNjg2OTQ1ODcz.GqqSgD.spsJ90LaRuUCwle4riZh6uzYXQJE1wRS2GgKho"  # copy from bot testing server
